services:
  server-go:
    build:
      context: .
      dockerfile: ./go/Dockerfile
    ports:
      - 8081:8081
    
  client-java:
    build: ./java
    platform: linux/amd64
    depends_on:
      - server-go
    environment:
      - SERVER_ADDR=server-go:8081
